# Builds Help/search-index.js: a plain-JS index (works from file://) with each page's
# title, headings and a short text excerpt for the site-wide search box.
$ErrorActionPreference = 'Stop'
$utf8 = [System.Text.UTF8Encoding]::new($false)
$help = $PSScriptRoot
$files = Get-ChildItem -Recurse $help -File -Filter *.html | Where-Object { $_.Name -ne 'index.html' } | Sort-Object FullName

$entries = New-Object System.Collections.Generic.List[string]

foreach ($f in $files) {
    $html = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)
    $rel = $f.FullName.Substring($help.Length + 1).Replace('\', '/')

    $title = ''
    if ($html -match '<title>([^<]*)</title>') { $title = $matches[1] -replace '\s*\|\s*Beep\.Skia Documentation$', '' }
    if (-not $title -and $html -match '<h1>([^<]*)</h1>') { $title = $matches[1] }

    $headings = @()
    foreach ($m in [regex]::Matches($html, '<h[23][^>]*>(.*?)</h[23]>')) {
        $h = $m.Groups[1].Value -replace '<[^>]+>', '' -replace '\s+', ' '
        $h = $h.Trim() -replace '&amp;', '&' -replace '&mdash;', '-' -replace '&rsaquo;', '>'
        if ($h) { $headings += $h }
    }

    # Body text excerpt: strip scripts/styles/tags and the page header chrome.
    $body = $html
    $body = [regex]::Replace($body, '(?s)<script.*?</script>', ' ')
    $body = [regex]::Replace($body, '(?s)<style.*?</style>', ' ')
    $body = [regex]::Replace($body, '(?s)<nav class="breadcrumb-nav".*?</nav>', ' ')
    $body = [regex]::Replace($body, '(?s)<div class="page-header".*?</div>', ' ')
    $body = [regex]::Replace($body, '(?s)<div class="toc".*?</div>', ' ')
    $body = [regex]::Replace($body, '<[^>]+>', ' ')
    $body = $body -replace '&amp;', '&' -replace '&mdash;', '-' -replace '&lt;', '<' -replace '&gt;', '>' -replace '&quot;', '"' -replace '&#39;', "'" -replace '&rsaquo;', '>'
    $body = $body -replace '\s+', ' '
    $body = $body.Trim()
    if ($body.Length -gt 1200) { $body = $body.Substring(0, 1200) }

    $escape = { param($s) ($s -replace '\\', '\\' -replace '"', '\"' -replace "`r", ' ' -replace "`n", ' ') }
    $line = '  { "t": "' + (& $escape $title) + '", "p": "' + $rel + '", "h": "' + (& $escape ($headings -join ' | ')) + '", "x": "' + (& $escape $body) + '" }'
    $entries.Add($line)
}

$js = "// Generated by _gen_search_index.ps1 - do not edit by hand.`nwindow.__BEEP_SKIA_SEARCH__ = [`n" + ($entries -join ",`n") + "`n];`n"
[System.IO.File]::WriteAllText((Join-Path $help 'search-index.js'), $js, $utf8)
Write-Output "wrote search-index.js with $($entries.Count) pages ($([math]::Round((Get-Item (Join-Path $help 'search-index.js')).Length / 1KB)) KB)"
