using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Beep.Skia.ERD
{
    /// <summary>
    /// Generates forward and rollback migration scripts from a <see cref="SchemaComparisonResult"/>.
    /// Dialect-aware DDL for SQL Server, PostgreSQL, MySQL, Oracle, SQLite, and ANSI.
    /// </summary>
    public class MigrationScriptGenerator
    {
        /// <summary>
        /// Generates the script that migrates the source schema to the target schema.
        /// </summary>
        public string GenerateForward(SchemaComparisonResult diff, DDLImporter.SQLDialect dialect = DDLImporter.SQLDialect.ANSI)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Forward migration (source -> target)");
            sb.AppendLine($"-- Generated by Beep.Skia on {DateTime.UtcNow:u}");
            sb.AppendLine();

            if (diff == null || !diff.HasChanges)
            {
                sb.AppendLine("-- No changes detected.");
                return sb.ToString();
            }

            // Drop FKs first so columns/tables can be modified safely.
            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedForeignKey))
                Append(sb, DropForeignKey(change.TableName, change.Constraint, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedConstraint))
                Append(sb, DropConstraint(change.TableName, change.Constraint, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedColumn))
                Append(sb, DropColumn(change.TableName, change.Column, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AddedTable))
                Append(sb, CreateTable(change.Table, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AddedColumn))
                Append(sb, AddColumn(change.TableName, change.Column, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AlteredColumn))
                Append(sb, AlterColumn(change.TableName, change.Column, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedTable))
                Append(sb, DropTable(change.TableName, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AddedForeignKey))
                Append(sb, AddForeignKey(change.TableName, change.Constraint, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AddedConstraint))
                Append(sb, AddConstraint(change.TableName, change.Constraint, dialect));

            return sb.ToString();
        }

        /// <summary>
        /// Generates the script that reverses <see cref="GenerateForward"/> (target -> source).
        /// </summary>
        public string GenerateRollback(SchemaComparisonResult diff, DDLImporter.SQLDialect dialect = DDLImporter.SQLDialect.ANSI)
        {
            var sb = new StringBuilder();
            sb.AppendLine("-- Rollback migration (target -> source)");
            sb.AppendLine($"-- Generated by Beep.Skia on {DateTime.UtcNow:u}");
            sb.AppendLine();

            if (diff == null || !diff.HasChanges)
            {
                sb.AppendLine("-- No changes to roll back.");
                return sb.ToString();
            }

            // Reverse order of the forward script with inverse operations.
            foreach (var change in diff.OfKind(SchemaChangeKind.AddedForeignKey))
                Append(sb, DropForeignKey(change.TableName, change.Constraint, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AddedConstraint))
                Append(sb, DropConstraint(change.TableName, change.Constraint, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AlteredColumn))
                Append(sb, AlterColumn(change.TableName, change.PreviousColumn, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AddedColumn))
                Append(sb, DropColumn(change.TableName, change.Column, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.AddedTable))
                Append(sb, DropTable(change.TableName, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedTable))
                Append(sb, CreateTable(change.PreviousTable, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedColumn))
                Append(sb, AddColumn(change.TableName, change.Column, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedForeignKey))
                Append(sb, AddForeignKey(change.TableName, change.Constraint, dialect));

            foreach (var change in diff.OfKind(SchemaChangeKind.RemovedConstraint))
                Append(sb, AddConstraint(change.TableName, change.Constraint, dialect));

            return sb.ToString();
        }

        // ── DDL builders ─────────────────────────────────────────────────────

        private static string? CreateTable(DDLImporter.TableInfo? table, DDLImporter.SQLDialect dialect)
        {
            if (table == null) return null;

            var lines = new List<string>();
            foreach (var column in table.Columns ?? new List<DDLImporter.ColumnInfo>())
            {
                lines.Add("  " + ColumnDefinition(column, dialect, inlinePrimaryKey: true));
            }
            foreach (var fk in (table.Constraints ?? new List<DDLImporter.ConstraintInfo>()).Where(c => !string.IsNullOrWhiteSpace(c?.ReferencedTable)))
            {
                lines.Add("  " + ForeignKeyClause(fk, dialect, table.TableName));
            }
            foreach (var constraint in (table.Constraints ?? new List<DDLImporter.ConstraintInfo>()).Where(IsTableConstraint))
            {
                lines.Add("  " + ConstraintClause(constraint, dialect, table.TableName));
            }

            var sb = new StringBuilder();
            sb.AppendLine($"CREATE TABLE {Quote(table.TableName, dialect)} (");
            sb.AppendLine(string.Join("," + Environment.NewLine, lines));
            sb.AppendLine(");");
            return sb.ToString();
        }

        private static string DropTable(string tableName, DDLImporter.SQLDialect dialect)
            => $"DROP TABLE {Quote(tableName, dialect)};";

        private static string? AddColumn(string tableName, DDLImporter.ColumnInfo? column, DDLImporter.SQLDialect dialect)
        {
            if (column == null) return null;

            var keyword = dialect == DDLImporter.SQLDialect.SQLServer ? "ADD" : "ADD COLUMN";
            var sb = new StringBuilder();
            sb.AppendLine($"ALTER TABLE {Quote(tableName, dialect)} {keyword} {ColumnDefinition(column, dialect, inlinePrimaryKey: false)};");

            // SQL Server cannot add a NOT NULL column with a default in one statement for existing rows.
            if (dialect == DDLImporter.SQLDialect.SQLServer && !column.IsNullable && !string.IsNullOrWhiteSpace(column.DefaultValue))
            {
                sb.AppendLine($"ALTER TABLE {Quote(tableName, dialect)} ADD CONSTRAINT {Quote($"df_{tableName}_{column.Name}", dialect)} DEFAULT {column.DefaultValue} FOR {Quote(column.Name, dialect)};");
            }
            return sb.ToString();
        }

        private static string DropColumn(string tableName, DDLImporter.ColumnInfo? column, DDLImporter.SQLDialect dialect)
            => $"ALTER TABLE {Quote(tableName, dialect)} DROP COLUMN {Quote(column?.Name, dialect)};";

        private static string? AlterColumn(string tableName, DDLImporter.ColumnInfo? column, DDLImporter.SQLDialect dialect)
        {
            if (column == null) return null;

            var type = RenderType(column);
            var nullability = column.IsNullable ? "NULL" : "NOT NULL";

            switch (dialect)
            {
                case DDLImporter.SQLDialect.SQLServer:
                    return $"ALTER TABLE {Quote(tableName, dialect)} ALTER COLUMN {Quote(column.Name, dialect)} {type} {nullability};";

                case DDLImporter.SQLDialect.PostgreSQL:
                    var sb = new StringBuilder();
                    sb.AppendLine($"ALTER TABLE {Quote(tableName, dialect)} ALTER COLUMN {Quote(column.Name, dialect)} TYPE {type};");
                    sb.AppendLine($"ALTER TABLE {Quote(tableName, dialect)} ALTER COLUMN {Quote(column.Name, dialect)} {(column.IsNullable ? "DROP NOT NULL" : "SET NOT NULL")};");
                    return sb.ToString().TrimEnd();

                case DDLImporter.SQLDialect.MySQL:
                    return $"ALTER TABLE {Quote(tableName, dialect)} MODIFY COLUMN {Quote(column.Name, dialect)} {type} {nullability};";

                case DDLImporter.SQLDialect.Oracle:
                    return $"ALTER TABLE {Quote(tableName, dialect)} MODIFY ({Quote(column.Name, dialect)} {type} {nullability});";

                case DDLImporter.SQLDialect.SQLite:
                    return $"-- SQLite does not support ALTER COLUMN; rebuild table '{tableName}' to change {column.Name} to {type} {nullability}.";

                default:
                    return $"ALTER TABLE {Quote(tableName, dialect)} ALTER COLUMN {Quote(column.Name, dialect)} SET DATA TYPE {type};";
            }
        }

        private static string? AddConstraint(string tableName, DDLImporter.ConstraintInfo? constraint, DDLImporter.SQLDialect dialect)
        {
            if (constraint == null) return null;
            if (dialect == DDLImporter.SQLDialect.SQLite)
                return $"-- SQLite does not support adding constraints via ALTER; rebuild table '{tableName}' to add {constraint.Type} ({constraint.Columns}).";

            return $"ALTER TABLE {Quote(tableName, dialect)} ADD {ConstraintClause(constraint, dialect, tableName)};";
        }

        private static string? DropConstraint(string tableName, DDLImporter.ConstraintInfo? constraint, DDLImporter.SQLDialect dialect)
        {
            if (constraint == null) return null;
            if (dialect == DDLImporter.SQLDialect.SQLite)
                return $"-- SQLite does not support dropping constraints via ALTER; rebuild table '{tableName}' to drop {constraint.Type} ({constraint.Columns}).";

            var name = ConstraintName(constraint, tableName);
            return dialect == DDLImporter.SQLDialect.MySQL && string.Equals(constraint.Type, "UNIQUE", StringComparison.OrdinalIgnoreCase)
                ? $"ALTER TABLE {Quote(tableName, dialect)} DROP INDEX {Quote(name, dialect)};"
                : $"ALTER TABLE {Quote(tableName, dialect)} DROP CONSTRAINT {Quote(name, dialect)};";
        }

        private static string ConstraintClause(DDLImporter.ConstraintInfo constraint, DDLImporter.SQLDialect dialect, string tableName)
        {
            var type = (constraint.Type ?? "CONSTRAINT").Trim().ToUpperInvariant();
            var name = ConstraintName(constraint, tableName);

            return type == "CHECK"
                ? $"CONSTRAINT {Quote(name, dialect)} CHECK ({constraint.Columns})"
                : $"CONSTRAINT {Quote(name, dialect)} UNIQUE ({QuoteList(constraint.Columns, dialect)})";
        }

        private static string ConstraintName(DDLImporter.ConstraintInfo constraint, string tableName)
        {
            if (!string.IsNullOrWhiteSpace(constraint.Name)) return constraint.Name;

            var type = (constraint.Type ?? "constraint").Trim().ToLowerInvariant();
            var prefix = type == "check" ? "ck" : "uq";
            var columns = (constraint.Columns ?? "cols").Replace(",", "_").Replace(" ", string.Empty);
            return $"{prefix}_{tableName}_{columns}";
        }

        private static bool IsTableConstraint(DDLImporter.ConstraintInfo constraint)
        {
            if (constraint == null || !string.IsNullOrWhiteSpace(constraint.ReferencedTable)) return false;
            var type = (constraint.Type ?? string.Empty).Trim().ToUpperInvariant();
            return type == "UNIQUE" || type == "CHECK";
        }

        private static string? AddForeignKey(string tableName, DDLImporter.ConstraintInfo? constraint, DDLImporter.SQLDialect dialect)
        {
            if (constraint == null) return null;
            return $"ALTER TABLE {Quote(tableName, dialect)} ADD {ForeignKeyClause(constraint, dialect, tableName)};";
        }

        private static string? DropForeignKey(string tableName, DDLImporter.ConstraintInfo? constraint, DDLImporter.SQLDialect dialect)
        {
            if (constraint == null) return null;

            if (string.IsNullOrWhiteSpace(constraint.Name))
            {
                return $"-- Drop foreign key on {tableName}({constraint.Columns}) referencing {constraint.ReferencedTable} (no constraint name recorded).";
            }

            return dialect == DDLImporter.SQLDialect.MySQL
                ? $"ALTER TABLE {Quote(tableName, dialect)} DROP FOREIGN KEY {Quote(constraint.Name, dialect)};"
                : $"ALTER TABLE {Quote(tableName, dialect)} DROP CONSTRAINT {Quote(constraint.Name, dialect)};";
        }

        private static string ColumnDefinition(DDLImporter.ColumnInfo column, DDLImporter.SQLDialect dialect, bool inlinePrimaryKey)
        {
            var sb = new StringBuilder();
            sb.Append($"{Quote(column.Name, dialect)} {RenderType(column)}");

            bool sqliteInlinePrimaryKey = dialect == DDLImporter.SQLDialect.SQLite && column.IsAutoIncrement;
            if (column.IsAutoIncrement)
            {
                sb.Append(dialect switch
                {
                    DDLImporter.SQLDialect.SQLServer => " IDENTITY(1,1)",
                    DDLImporter.SQLDialect.MySQL => " AUTO_INCREMENT",
                    DDLImporter.SQLDialect.SQLite => " PRIMARY KEY AUTOINCREMENT",
                    _ => " GENERATED BY DEFAULT AS IDENTITY"
                });
            }

            sb.Append(column.IsNullable ? " NULL" : " NOT NULL");

            if (inlinePrimaryKey && column.IsPrimaryKey && !sqliteInlinePrimaryKey)
                sb.Append(" PRIMARY KEY");

            if (!string.IsNullOrWhiteSpace(column.DefaultValue))
                sb.Append($" DEFAULT {column.DefaultValue}");

            return sb.ToString();
        }

        private static string ForeignKeyClause(DDLImporter.ConstraintInfo constraint, DDLImporter.SQLDialect dialect, string tableName)
        {
            var name = string.IsNullOrWhiteSpace(constraint.Name)
                ? $"fk_{tableName}_{(constraint.Columns ?? "cols").Replace(",", "_").Replace(" ", string.Empty)}"
                : constraint.Name;

            var sb = new StringBuilder();
            sb.Append($"CONSTRAINT {Quote(name, dialect)} FOREIGN KEY ({QuoteList(constraint.Columns, dialect)}) REFERENCES {Quote(constraint.ReferencedTable, dialect)} ({QuoteList(constraint.ReferencedColumns, dialect)})");
            if (!string.IsNullOrWhiteSpace(constraint.OnDelete)) sb.Append($" ON DELETE {constraint.OnDelete}");
            if (!string.IsNullOrWhiteSpace(constraint.OnUpdate)) sb.Append($" ON UPDATE {constraint.OnUpdate}");
            return sb.ToString();
        }

        private static string RenderType(DDLImporter.ColumnInfo column)
        {
            var type = string.IsNullOrWhiteSpace(column.DataType) ? "TEXT" : column.DataType.Trim();
            if (type.Contains("(")) return type;

            if (column.MaxLength.HasValue) return $"{type}({column.MaxLength.Value})";
            if (column.Precision.HasValue)
                return column.Scale.HasValue ? $"{type}({column.Precision.Value},{column.Scale.Value})" : $"{type}({column.Precision.Value})";
            return type;
        }

        private static string Quote(string? identifier, DDLImporter.SQLDialect dialect)
        {
            if (string.IsNullOrWhiteSpace(identifier)) return string.Empty;
            return dialect switch
            {
                DDLImporter.SQLDialect.SQLServer => $"[{identifier}]",
                DDLImporter.SQLDialect.MySQL => $"`{identifier}`",
                _ => $"\"{identifier}\""
            };
        }

        private static string QuoteList(string? commaSeparated, DDLImporter.SQLDialect dialect)
        {
            if (string.IsNullOrWhiteSpace(commaSeparated)) return string.Empty;
            return string.Join(", ", commaSeparated
                .Split(',')
                .Select(c => Quote(c.Trim(), dialect)));
        }

        private static void Append(StringBuilder sb, string? statement)
        {
            if (string.IsNullOrWhiteSpace(statement)) return;
            sb.AppendLine(statement.TrimEnd());
            sb.AppendLine();
        }
    }
}